name: Je suis eclectique
url: http://jesuiseclectique.com
markdown: redcarpet
highlighter: pygments
fullname: Luisa Fernanda
<<<<<<< HEAD
baseurl: ""
=======
baseurl: /Je-suis-eclectique
>>>>>>> newindex
permalink: /:categories/:year/:month/:title
excerpt_separator: ""
categories:  Tech Creativity Illustration Daily
paginate: 10
