name: Je suis éclectique
url: http://jesuiseclectique.com
description: A site about finding and propelling your artistic and creative expression.
markdown: redcarpet
highlighter: pygments
fullname: Luisa Fernanda
baseurl: ""
permalink: /:categories/:year/:month/:title
excerpt_separator: ""
categories:  Tech Creativity Illustration Daily


