name: Je suis eclectique
url: http://jesuiseclectique.com
markdown: redcarpet
highlighter: pygments
fullname: Luisa Fernanda
baseurl: /jesuiseclectique.com
permalink: /:categories/:year/:month/:title
excerpt_separator: ""
categories:  Tech Creativity Illustration Daily
paginate: 10
