name: Je suis éclectique
url: http://jesuiseclectique.com
markdown: redcarpet
highlighter: pygments
fullname: Luisa Fernanda
baseurl: ""
permalink: /:categories/:year/:month/:title
excerpt_separator: ""
categories:  Tech Creativity Illustration Daily
paginate: 10
